import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

import AnimatedCursor from "react-animated-cursor";
const inter = Inter({ subsets: ["latin"] });
import Footer from "@/components/Footer";
export const metadata: Metadata = {
  title: "Agentia World",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <AnimatedCursor
            innerSize={8}
            outerSize={35}
            innerScale={2}
            outerScale={2}
            outerAlpha={0}
            innerStyle={{
              backgroundColor: "white",
            }}
            outerStyle={{
              border: "2px solid white",
            }}
          />
        <Navbar/>{children}
        <Footer/></body>
    </html>
  );
}
